### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-valerialp#1]
Super @valerialp  !!!

Here you have some tips to improve the exercise:

- [x] Don't use a loop to resolve the counter, a good simple assignment will suffice ;)
- [x] Since you are using 'Number' instead of 'parseInt', let's investigate the difference ;)
- [x] You are converting to number in each condition of the if/else, what about making it only one time per click, saving the result into a constant and reusing it?
- [x] Move variables and constants declarations to the top of the file
- [x] Remove commented code
- [x] Improve the name of your handler.
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by valerialp** [comment]
Hello! I think I already made the changes you advised me. I used Number because I saw it in a Node workshop and I could not get the strings to be converted to numbers (then I saw that I wrote parseint instead of parseInt). I want to continue improving the exercise and putting more things into it.

**Comment by nasivuela** [comment]
Soooo cool!

![](https://media.giphy.com/media/LrN9NbJNp9SWQ/giphy.gif)
